%YAML 1.2
---
- hosts: devmachines
  user: "{{user}}"
  roles:
    - role: common
    - role: apt-node
    - role: rbenv
    - role: ruby-build
    - role: rails
    - role: elasticsearch
    - role: dev
